service: lambda-send-mail # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
